name: 'KiCad command line Action'
description: 'Automate KiCad tasks, e.g. check ERC/DRC on pull requests or generate production files for releases'

inputs:
  kicad_sch:
    description: 'Path to .kicad_sch file'
  sch_erc_file:
    description: 'Output filename of ERC report'
  sch_pdf_file:
    description: 'Output filename of PDF schematic'
  sch_bom_file:
    description: 'Output filename of BOM'
  sch_bom_preset:
    description: 'Name of a BOM preset setting to use'
  report_format:
    description: 'ERC and DRC report files format'
    type: choice
    options:
      - json
      - report
    default: 'report'
  kicad_pcb:
    description: 'Path to .kicad_pcb file'
  pcb_drc_file:
    description: 'Output filename for DRC report'
  pcb_gerbers_file:
    description: 'Output filename of Gerbers ZIP'
  pcb_gerbers_layers:
    description: 'Output layers to generate from PCB'
  pcb_centroids_file:
    description: 'Output filename of centroid (component placement)'
  pcb_centroids_format:
    description: 'Output format to generate centroid (component placement) files from PCB'
    default: 'ascii'
  pcb_top_image_file:
    description: 'Ouput filename for PCB top view'
  pcb_top_image_zoom:
    description: 'Ouput zoom for PCB top view'
  pcb_top_image_quality:
    description: 'Ouput image file render quality. Options: basic, high, user [nargs=0..1]'
  pcb_top_image_width:
    description: 'Ouput image file width for PCB top view'
  pcb_top_image_height:
    description: 'Ouput image file height for PCB top view'
  pcb_bottom_image_file:
    description: 'Ouput filename for PCB bottom view'
  pcb_bottom_image_zoom:
    description: 'Ouput zoom for PCB bottom view'
  pcb_bottom_image_width:
    description: 'Ouput image file width for PCB bottom view'
  pcb_bottom_image_height:
    description: 'Ouput image file height for PCB top view'
  pcb_bottom_image_quality:
    description: 'Ouput image file render quality. Options: basic, high, user [nargs=0..1]'
  pcb_model_file:
    description: 'Output filename of PCB model'
  pcb_model_flags:
    description: 'Flags to add when exporting STEP files'
    default: '--no-unspecified --no-dnp --include-tracks  --include-pads  --include-zones'
  
runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'zap'
  color: 'gray-dark'
